version: '3'
services:
  order-service:
    container_name: order-api
    build: .
    depends_on:
      - order-postgres
    ports: 
      - 50053:50053
    restart: on-failure
    volumes:
      - ./:/usr/src/app-order/
    networks:
      - fullstack

  order-postgres:
    image: postgres:latest
    container_name: order_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
    
networks:
  fullstack:
    external: true

volumes:
  api:
  database_postgres:

